### ISSUE TITLE
[Feature] 멘토링 취소 사유 추가

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/backend#116]
- manito42/Frontend#180
- manito42/Frontend#190

**Description**
- 멘토링 취소 프로세스 추가

**Todo**
- [x] 취소사유 데이터베이스에 영속화할건지 결정
  - [x] 1에따른 스키마 변경
- [x] API문서 작성
- [x] DTO 변경
- [x] 메일 템플릿변경
- [x] Notification 모듈 변경

**Comment by koreanddinghwan** [comment]
<img width="680" alt="Screen Shot 2023-09-29 at 6 38 36 PM" src="https://github.com/manito42/backend/assets/76278794/3955e12a-8984-4815-8b47-6ee62282d21b">

**Comment by koreanddinghwan** [comment]
취소 사유 추가하면서 코드 전체적으로 리팩토링했습니다. 
불필요하게 여러번 만들어지는 객체 정리했고, 
  - repository는 모두 prismamodule에서 관리하고, 다른 모듈에서 prismamodule을 import하도록 변경했습니다.
  - jwtconfigmodule, ftconfigmodule 등에서 각 strategy, guard를 초기화하며, guard만 export합니다. 이를 사용하는 모듈은 각 모듈만 import합니다.
  - home/search의 경우, mentorprofileservice를 사용하는데, mentorprofilemodule을 import해 여러 service instance가 초기화되지 않도록 변경했습니다.
