### ISSUE TITLE
[Feature] image resizer

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/backend#138]
**Description**
- 인트라 cdn이 불안정함에따라 별도의 image 저장 프로세스가 필요하게 되었습니다.
- 별도의 lambda를 사용하는 것이 아닌, api 서버 자원을 그대로 사용합니다.(유휴 상태 자원이 많음)
- [S3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/) + [sharp](https://github.com/lovell/sharp) 를 사용합니다.

<br>

**Todo**
- [ ] 이미 login절차에서 42 oauth 서버와 통신이 느린 상태인데, 이미지 resize 과정까지 포함하면 더 느려질 것. 어떻게 처리할 것인가?
- [ ] 사용할 image resizer lib 선택
- [ ] 저장할 이미지 형식, 비율, 크기(w,h)  지정
- [ ] 서버 모듈 구조 선택(notification module이 이미 aws sdk와 묶여있음. 이와 분리할건지)
- [ ] s3 앞에 api-gateway를 붙여서 CORS관리 할 것인지 선택

**Comment by JuneParkCode** [comment]
아니 이걸 그새...제가 하려고했는데 ㅋㅋ.확인해보겠습니다~

**Comment by JuneParkCode** [comment]
1. 초기 이미지를 default 지정으로 해걀
- 굳이 인트라 프로필 변환해서 들고올 필요는 없을 것 같습니다. 이미지 추가가 가능한 이상 default를 별도로 두고, 이후에 유저가 직접 추가할 수 있도록 해주면 좋을 듯 합니다.

**Comment by koreanddinghwan** [comment]
<img width="1547" alt="스크린샷 2023-10-10 16 05 08" src="https://github.com/manito42/backend/assets/76278794/94119fb6-8782-4d26-9ef8-f3771cf28e55">

<img width="1592" alt="스크린샷 2023-10-10 16 05 36" src="https://github.com/manito42/backend/assets/76278794/e26a4a7e-13a1-4c0a-ab0c-2fbb70f8f0e5">


원본 인트라 이미지 -> 300kb

160 * 120 , jpeg : 2.6kb
160 * 120 , webp : 1.3kb

**Comment by JuneParkCode** [comment]
default -> 인트라 default 말고 그냥 빈 아바타 이미지임당

**Comment by JuneParkCode** [comment]
>[S3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/) + [sharp](https://github.com/lovell/sharp) 를 사용합니다.
resizer lib 는 sharp 쓰는것 아닌가여?

**Comment by koreanddinghwan** [comment]
> default -> 인트라 default 말고 그냥 빈 아바타 이미지임당

그럼 default image는 프론트 서버에 두고, 서버에서 '' 이렇게 리턴되면 default image렌더링하시면될것같아요

**Comment by JuneParkCode** [comment]
w, h 는 300px * 300px 안쪽이면 춤분합니다.

**Comment by koreanddinghwan** [comment]
모듈 구조는 어떻게 할까요? upload 모듈 별도로 만들어두는게 낫지않나..

**Comment by koreanddinghwan** [comment]
notification쪽에서 SES 따로 사용하고있는데, S3랑 SES 모듈 합쳐서 AWS 모듈로 만들어서 처리하는것도 어떤가싶기도하구

**Comment by JuneParkCode** [comment]
AWS를 별도로 분리하고 그거 가져다쓰게 해야할 것 같네여 upload 는 당근 따로 두고...

**Comment by koreanddinghwan** [comment]
> AWS를 별도로 분리하고 그거 가져다쓰게 해야할 것 같네여 upload 는 당근 따로 두고...

#144
