### ISSUE TITLE
[Todo] intra profile image를 default 가 아닌 작은 사이즈를 가져오도록 변경

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#148]
**Description**
- intra profile image 가 기존의 경우 default image 를 가져오도록 설정되어있음.
- 약 200kb 이상으로 여러 멘토가 노출되는 home 에서 로드 시간이 오래 걸림
- middle 사이즈 이하로 설정하여 이를 해결할 수 있음.

**Todo**
- [ ] 로그인이 해제되어 intra에 접근하여 로그인할 때, 42 api 로부터 profile image 를 업데이트시키도록 변경함

**etc**
- [ ] 기존 멘토의 경우 별도 스크립트를 통해서 변경(?)
  - [ ] 이것이 필요한가? 별도로 api 접근해서 쭉 바꾸는 스크립트를 작성 필요
  - [ ] NestJS 내에서 하는 것보다 외부 스크립트로 작성하는게 바람직할 것 같은데, SQL 을 별도로 연결해서 작업해야하는 불편함이 있음.
  - [ ] NestJS 에서 별도 작업할 경우, 42 API 모듈을 작성해서 접근하는 것이 나을 것 같음.
- [ ] @JuneParkCode 가 작업하겠습니다. 요즘 코딩을 너무 안해서 하고 싶네요...

**Comment by JuneParkCode** [comment]
요번주 내로 작업해서 변경하겠습니다.
