### ISSUE TITLE
[Infra] 서버 이전

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#149]
**Description**
- AWS 기반 서버 인프라 홈서버로 이전

**Todo**
- [ ] Router 53 으로 연결된 도메인 이전 작업 필요
  - [ ] 도메인의 경우 Vercel 에 귀속되어있음. 네임서버 작업을 CloudFront or AWS 이용하여 변경 필요
  - [ ] SSL 인증 별도 필요
- [ ] 새로운 서버 구조 설계
  - [ ] 11월 1주차에 백엔드 회의 필요
- [ ] Docker Container 기반으로 서버 설계 
- [ ] DB 마이그레이션
  - [ ] RDS 에 저장된 데이터 옮기기
- [ ] CI/CD

**etc**
- 회의 이후 Todo list 따로 정리 필요함.

**Comment by koreanddinghwan** [comment]
https://github.com/orgs/manito42/discussions/7

**Comment by koreanddinghwan** [comment]
# DB dump작업

1. 바스티온 호스트 접속
2. `mysqldump -u "데이터베이스 유저 명" -h"데이터베이스주소" -p "덤프할 데이터베이스 명" > dump.sql`
3. 홈서버에서 scp명령어를 사용해 바스티온호스트의 dump.sql 복사해서 홈서버로 이동
    - `scp ec2-user@manito_dev:/home/ec2-user/dump.sql ../golang-with-k8s/generated`
4. dump.sql을 홈서버의 데이터베이스에 적용 `mysql -h"127.0.0.1" -u root -p manito < dump.sql`

**Comment by JuneParkCode** [comment]
- Name Server -> AWS Route53 or Cloudflare(free)
- k3s or Minikube ? (사실 별 상관 없을듯..? ingress controller 쪽만 보면 될 것 같음)
- DB  -> RDS or 팟으로 따로..?
- Ingress controller -> traefik or nginx?
- docker registar -> 이미 만들어두신 것으로...알고 있음..

위 사항중에서 혹시 결정된거 있으면 따로 알려주세용... DB 는 RDS 굳이 안해도 그냥 돌려도 상관 없을듯...

**Comment by koreanddinghwan** [comment]
1. NameServer 유지(Route53)
2. minikube/k3s 아무거나, ingress controller 아무거나 사용, 외부에서 관리용도로 접근시 ssh로 접속 or kubectl port forward
3. DB -> hellm chart사용해서 관리.
4. https://kubernetes.io/ko/docs/tasks/access-application-cluster/ingress-minikube
5. docker registry/공개되어있음. CI로 돌려야함

**Comment by koreanddinghwan** [comment]
정신이없네요,, 인턴에 과제에 시간 투자 많이 못해서 죄송합니다

**Comment by JuneParkCode** [comment]
- 11.30 05:30 기준 dump 완료
- 당분간 docker-compose 기반으로 작동
- k3s 사용
- ingress controller -> nginx 사용

- 도커 레지스트리의 경우 우선은 제 쪽에서 처리좀 해보겠습니다. docker-compose 기반 작동시에는 Dockerfile 활용예정.
