### ISSUE TITLE
AWS 아키텍처 구축

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#18]
# TODO
## Route 53
- [x] #20 

## ELB

- [x] #22
- [x] test Auto Scaling Group 생성(min/max 1개로) #22 
- [x] ELB -> test ASG 연결 #22 
- [x] Route53=> SSL 적용 #22 
- [x] CodeDeploy용 test s3 bucket 생성 #22 
- [x] CodeDeploy IAM Role #22 

## RDS
- [x] #19

## Code Deploy
- [x] CI/CD 를 위한 Code Deploy

다른 할 일이 있으면 추가 부탁드립니다.

**Comment by JuneParkCode** [comment]
세부 TODO 의 경우 별도의 이슈 등록 및 `AWS Architecture` 마일스톤으로 등록 부탁드립니다.
