### ISSUE TITLE
Route 53 도메인 설정

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#20]
# TODO
- #18
## Route 53
- [x] vercel 에 register 된 Domain AWS 로 네임서버 이전
- [x] api.42manito.com -> api 서버로 활용
- [x] 42manito.com -> 메인 프론트 페이지
- [x] api.dev.42manito.com -> 개발 API 서버
- [x] dev.42manito.com -> 개발 프론트

## EC2
- [x] 개발용 / 배포용 구분
