### ISSUE TITLE
[Feature] AWS SES 연동

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#36]
#AWS SES
## TODO
- [x] @42manito.com 으로 메일링
- [ ] Production Level 로 승격 필요
  - [ ] 실제 Frontend 페이지가 나오고 설정할 수 있을 것으로 보임.
- [ ] 기본 200 mail / 24h 이기 때문에, 업그레이드 요청 필요
- [x] 메일 발신을 위해서 IAM 설정 필요
- [ ] 메일 수신 가능해야함 (별도 문의 메일등 수신을 위함)
## Plan
- 우선은 node mailer + 공용 이메일 서비스 사용
- 제품 나오면 샌드박스에서 나오도록 요청하고, SES 와 연동해야함.
  - 샌드박스 내에서 @student.42seoul.kr 으로 메일이 가지 않음. (*인증되지 않음)

**Comment by JuneParkCode** [comment]
- SES 물려서하는 것보다 구글 계정에 메일 별칭 지정하는게 나을수도..?

**Comment by JuneParkCode** [comment]
- 메일 수신의 부분의 경우 당장 필요하지 않은 부분이므로, 추후에 구현하도록 함.
